language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
# pypy3 removed due to flask 0.11 incompatibility
env:
  - RIPOZO="ripozo"
  - RIPOZO="git+git://github.com/vertical-knowledge/ripozo.git@master"
install:
  - pip install coveralls
  - pip install -U $RIPOZO
  - python setup.py -q install
script:
  coverage run --source=flask_ripozo setup.py test
after_success:
  coveralls
